server:
  port: 8083
spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql:/TicketDB?createDatabaseIfNotExist=true
    username: root
    password: ijse@200108
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka