package lk.ijse.vehicleservice.dto;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class VehicleReqRes {
    @Null(message = "Id is generated by the program")
    private Long id;

    @NotNull(message = "License Plate cannot be null")
    private String licensePlate;

    @NotNull(message = "Model cannot be null")
    private String model;

    @NotNull(message = "Brand cannot be null")
    private String brand;

    @NotNull(message = "UserId cannot be null")
    private Long userId;
}
