package lk.ijse.paymentservice.dto;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class PaymentReqRes {
    @Null(message = "Payment ID is auto generated by program")
    private Long id;
    @Null(message = "Payment date is added by program")
    private LocalDateTime dateTime;
    @NotNull(message = "Payment amount is required")
    private Double amount;
    @NotNull(message = "Ticket Id is required")
    private Long ticketId;
}
